/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account
 */
export interface AccountQboData {
  Name: string;
  SubAccount: boolean;
  FullyQualifiedName: string;
  Active: boolean;
  Classification: "Asset" | "Equity" | "Expense" | "Liability" | "Revenue";
  AccountType: string;
  AccountSubType: string;
  CurrentBalance: number;
  CurrentBalanceWithSubAccounts: number;
  CurrencyRef: {
    value: string;
    name?: string;
  };
  domain: string;
  sparse: boolean;
  Id: string;
  SyncToken: string;
  MetaData: {
    CreateTime?: string;
    LastUpdatedTime?: string;
  };
  ParentRef?: {
    value?: string;
  };
}
