/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/companyinfo
 */
export interface CompanyInfoQboData {
  Id: string;
  SyncToken: string;
  CompanyName?: string;
  CompanyAddr?: Address;
  LegalAddr?: Address;
  SupportedLanguages?: string;
  Country?: string;
  Email?: Email;
  WebAddr?: Uri;
  NameValue?: {
    Name?: string;
    Value?: string;
  }[];
  FiscalYearStartMonth?: string;
  CustomerCommunicationAddr?: Address;
  PrimaryPhone?: Phone;
  LegalName?: string;
  MetaData?: {
    CreateTime?: string;
    LastUpdatedTime?: string;
  };
  CompanyStartDate?: string;
  domain?: string;
  sparse?: boolean;
  CustomerCommunicationEmailAddr?: Email;
}
/**
 * QBO mailing address
 */
export interface Address {
  Id: string;
  PostalCode?: string;
  City?: string;
  Country?: string;
  Line5?: string;
  Line4?: string;
  Line3?: string;
  Line2?: string;
  Line1?: string;
  Lat?: string;
  Long?: string;
  CountrySubDivisionCode?: string;
}
/**
 * QBO email address
 */
export interface Email {
  Address?: string;
}
/**
 * QBO website URI
 */
export interface Uri {
  URI?: string;
}
/**
 * QBO phone number object
 */
export interface Phone {
  FreeFormNumber?: string;
}
