/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/customer
 */
export interface CustomerQboData {
  Id: string;
  SyncToken: string;
  DisplayName?: string;
  Title?: string;
  GivenName?: string;
  MiddleName?: string;
  Suffix?: string;
  FamilyName?: string;
  PrimaryEmailAddr?: Email;
  ResaleNum?: string;
  SecondaryTaxIdentifier?: string;
  ARAccountRef?: {
    value: string;
    name?: string;
  };
  DefaultTaxCodeRef?: {
    value: string;
    name?: string;
  };
  PreferredDeliveryMethod?: string;
  GSTIN?: string;
  SalesTermRef?: {
    value: string;
    name?: string;
  };
  CustomerTypeRef?: {
    value: string;
  };
  Fax?: Phone;
  BusinessNumber?: string;
  BillWithParent?: boolean;
  CurrencyRef?: {
    value: string;
    name?: string;
  };
  Mobile?: Phone;
  Job?: boolean;
  BalanceWithJobs?: number;
  PrimaryPhone?: Phone;
  OpenBalanceDate?: Date;
  Taxable?: boolean;
  AlternatePhone?: Phone;
  MetaData?: {
    CreateTime?: string;
    LastUpdatedTime?: string;
  };
  ParentRef?: {
    value: string;
    name?: string;
  };
  Notes?: string;
  WebAddr?: Uri;
  Active?: boolean;
  CompanyName?: string;
  Balance?: number;
  ShipAddr?: Address;
  PaymentMethodRef?: {
    value: string;
    name?: string;
  };
  IsProject?: boolean;
  Source?: string;
  PrimaryTaxIdentifier?: string;
  GSTRegistrationType?: string;
  PrintOnCheckName?: string;
  BillAddr?: Address;
  FullyQualifiedName?: string;
  Level?: number;
  TaxExemptionReasonId?: number;
  domain?: string;
  sparse?: boolean;
  V4IDPseudonym?: string;
  ClientEntityId?: string;
}
/**
 * QBO email address
 */
export interface Email {
  Address?: string;
}
/**
 * QBO phone number object
 */
export interface Phone {
  FreeFormNumber?: string;
}
/**
 * QBO date string
 */
export interface Date {
  date?: string;
}
/**
 * QBO website URI
 */
export interface Uri {
  URI?: string;
}
/**
 * QBO mailing address
 */
export interface Address {
  Id: string;
  PostalCode?: string;
  City?: string;
  Country?: string;
  Line5?: string;
  Line4?: string;
  Line3?: string;
  Line2?: string;
  Line1?: string;
  Lat?: string;
  Long?: string;
  CountrySubDivisionCode?: string;
}
