/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/transactionlist
 */
export interface NameReportTableTransactionsListColumnQboData {
  Header: {
    Time: string;
    ReportName:
      | "AccountList"
      | "AgedPayableDetail"
      | "AgedPayables"
      | "AgedReceivableDetail"
      | "AgedReceivables"
      | "BalanceSheet"
      | "CashFlow"
      | "ClassSales"
      | "CustomerBalance"
      | "CustomerBalanceDetail"
      | "CustomerIncome"
      | "CustomerSales"
      | "DepartmentSales"
      | "GeneralLedger"
      | "InventoryValuationSummary"
      | "ItemSales"
      | "JournalReport"
      | "ProfitAndLoss"
      | "ProfitAndLossDetail"
      | "TaxSummary"
      | "TransactionList"
      | "TransactionListByCustomer"
      | "TransactionListByVendor"
      | "TransactionListWithSplits"
      | "TrialBalance"
      | "TrialBalanceFR"
      | "VendorBalance"
      | "VendorBalanceDetail"
      | "VendorExpenses";
    StartPeriod?: string;
    EndPeriod?: string;
  };
  Columns: {
    Column: {
      ColTitle: string;
      ColType: string;
      MetaData: {
        Name: string;
        Value: string;
      }[];
    };
  };
  Rows: {
    Row: {
      Header: {
        ColData: {
          value?: string;
          id?: string;
        };
      };
      Rows: {
        Row: {
          ColData: {
            value?: string;
            id?: string;
          }[];
        }[];
      };
    }[];
  };
}
